// ERRORS
export const EMPTY_ERRORS = 'EMPTY_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

// ADMIN
export const ADD_ADMIN = 'ADD_ADMIN';
export const BEFORE_ADMIN = 'BEFORE_ADMIN';
export const LOGIN_ADMIN = 'LOGIN_ADMIN';
export const GET_ADMIN = 'GET_ADMIN';
export const GET_ADMINS = 'GET_ADMINS';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const GET_USER_VERIFY = 'GET_USER_VERIFY';
export const BEFORE_USER_VERIFY = 'BEFORE_USER_VERIFY';
export const SET_PASSWORD = 'SET_PASSWORD';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SENT = 'VERIFY_EMAIL_SENT';


// ROLES
export const ADD_ROLE = 'ADD_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const GET_ROLE = 'GET_ROLE';
export const GET_ROLES = 'GET_ROLES';
export const BEFORE_ROLE = 'BEFORE_ROLE';
export const BEFORE_PERMISSION = 'BEFORE_PERMISSION';
export const GET_PERMISSION = 'GET_PERMISSION';
export const SET_LOADER_ROLE = 'SET_LOADER_ROLE';
export const REMOVE_LOADER_ROLE = 'REMOVE_LOADER_ROLE';

// USERS
export const BEFORE_STUDENT = 'BEFORE_STUDENT';
export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENT = 'GET_STUDENT';
export const UPSERT_STUDENT = 'UPSERT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPSERT_ADDRESS = 'UPSERT_ADDRESS';
export const STUDENT_VERIFICATION = 'STUDENT_VERIFICATION';
export const UPSERT_EXTRACT = 'UPSERT_EXTRACT';
export const GET_All_STUDENTS = 'GET_All_STUDENTS';
// INTERVIEWER
export const BEFORE_INTERVIEWER = 'BEFORE_INTERVIEWER';
export const GET_INTERVIEWERS = 'GET_INTERVIEWERS';
export const GET_INTERVIEWER = 'GET_INTERVIEWER';
export const UPSERT_INTERVIEWER = 'UPSERT_INTERVIEWER';
export const DELETE_INTERVIEWER = 'DELETE_INTERVIEWER';
export const INTERVIEWER_VERIFICATION = 'INTERVIEWER_VERIFICATION';
export const GET_All_INTERVIEWERS = 'GET_All_INTERVIEWERS';
// semester
export const BEFORE_SEMESTER = 'BEFORE_SEMESTER';
export const GET_SEMESTERS = 'GET_SEMESTERS';
export const GET_SEMESTER = 'GET_SEMESTER';
export const UPSERT_SEMESTER = 'UPSERT_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';

//loan Applications
export const BEFORE_APPLICATION = 'BEFORE_APPLICATION';
export const GET_APPLCIATIONS = 'GET_APPLCIATIONS';

// Emails
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL = 'GET_EMAIL';
export const BEFORE_EMAIL = 'BEFORE_EMAIL';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const EDIT_SETTINGS = 'EDIT_SETTINGS';
export const BEFORE_SETTINGS = 'BEFORE_SETTINGS';
// USER EMAIL TEMPLATE
export const GET_EMAIL_TYPES = 'GET_EMAIL_TYPES'
export const BEFORE_EMAIL_TYPE = 'BEFORE_EMAIL_TYPE'
export const DELETE_EMAIL_TYPE = 'DELETE_EMAIL_TYPE'
export const CREATE_EMAIL_TYPE = 'CREATE_EMAIL_TYPE'
export const GET_EMAIL_TYPE = 'GET_EMAIL_TYPE'
export const EDIT_EMAIL_TYPE = 'EDIT_EMAIL_TYPE'
// DASHBOARD
export const BEFORE_DASHBOARD = 'BEFORE_DASHBOARD'
export const GET_DASHBOARD = 'GET_DASHBOARD'

//CONTENT MANAGEMENT
export const GET_CONTENT_PAGE = 'GET_CONTENT_PAGE'
export const GET_CONTENT_PAGES = 'GET_CONTENT_PAGES'
export const EDIT_CONTENT_PAGE = 'EDIT_CONTENT_PAGE'
export const DELETE_CONTENT_PAGE = 'DELETE_CONTENT_PAGE'
export const ADD_CONTENT_PAGE = 'ADD_CONTENT_PAGE'
export const BEFORE_CONTENT = 'BEFORE_CONTENT'

// USER EMAIL TEMPLATE
export const GET_USER_EMAIL_TEMPLATES = 'GET_USER_EMAIL_TEMPLATES'
export const BEFORE_USER_EMAIL_TEMPLATE = 'BEFORE_USER_EMAIL_TEMPLATE'
export const DELETE_USER_EMAIL_TEMPLATE = 'DELETE_USER_EMAIL_TEMPLATE'
export const CREATE_USER_EMAIL_TEMPLATE = 'CREATE_USER_EMAIL_TEMPLATE'
export const GET_USER_EMAIL_TEMPLATE = 'GET_USER_EMAIL_TEMPLATE'
export const EDIT_USER_EMAIL_TEMPLATE = 'EDIT_USER_EMAIL_TEMPLATE'
export const GET_USER_EMAIL_TYPES = 'GET_USER_EMAIL_TYPES'





